# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'aprobacion_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CONVERTIDA_EN_PEDIDO', 'Convertida en pedido')], default='BORRADOR', max_length=30)),
                ('total_estimado', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_estimado', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cantidad_preparada', models.IntegerField(default=0)),
                ('precio_unitario_historico', models.IntegerField()),
                ('descuento', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EN_PICKING', 'En picking'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('tipo_venta', models.CharField(choices=[('WEBPAY', 'WebPay'), ('TRANSFERENCIA', 'Transferencia'), ('MAYORISTA', 'Mayorista'), ('CREDITO_INSTITUCIONAL', 'Crédito institucional')], max_length=30)),
                ('tipo_despacho', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express')], default='NORMAL', max_length=10)),
                ('prioridad_medica', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=10)),
                ('fecha_requerida_entrega', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.IntegerField(default=0)),
                ('descuento_total', models.IntegerField(default=0)),
                ('monto_neto', models.IntegerField(default=0)),
                ('monto_iva', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
    ]
