"""
Django settings for medistockbackend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

#CARGA LAS VARIABLES DE ENTORNO
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
CHILEXPRESS_BASE_URL = os.getenv("CHILEXPRESS_BASE_URL")
CHILEXPRESS_API_VERSION = os.getenv("CHILEXPRESS_API_VERSION")
CHILEXPRESS_API_KEY_OT = os.getenv("CHILEXPRESS_API_KEY_OT")
CHILEXPRESS_API_KEY_COBERTURA = os.getenv("CHILEXPRESS_API_KEY_COBERTURA")
CHILEXPRESS_TCC = os.getenv("CHILEXPRESS_TCC")
CHILEXPRESS_API_KEY_COTIZADOR = os.getenv("CHILEXPRESS_API_KEY_COTIZADOR")

MEDISTOCK_RUT      = os.getenv("MEDISTOCK_RUT")
MEDISTOCK_TELEFONO = os.getenv("MEDISTOCK_TELEFONO")
MEDISTOCK_EMAIL    = os.getenv("MEDISTOCK_EMAIL")

FRONTEND_BASE_URL = "http://3.232.238.104"
BACKEND_BASE_URL = "http://3.232.238.104"
TRANSBANK_ENVIRONMENT = os.getenv("TRANSBANK_ENVIRONMENT")

TRANSBANK_WEBPAY_COMMERCE_CODE = os.getenv("TRANSBANK_WEBPAY_COMMERCE_CODE")
TRANSBANK_WEBPAY_API_KEY = os.getenv("TRANSBANK_WEBPAY_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [ "3.232.238.104",
    "localhost",
    "127.0.0.1",]

AUTH_USER_MODEL = 'accounts.Usuario'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    "rest_framework_simplejwt.token_blacklist",

    'apps.accounts',

    'apps.inventory',
    'apps.locations',
    'apps.orders',
    'apps.logistics',
    'apps.payments',
    'apps.billing',
    'apps.procurement',
    'apps.integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medistockbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medistockbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'NAME': os.getenv('DB_NAME_REMOTE', 'medistock_db'),
    #    'ENGINE': os.getenv('DB_ENGINE_REMOTE', 'django.db.backends.mysql'),
    #    'HOST': os.getenv('DB_HOST_REMOTE', '127.0.0.1'),
    #    'PORT': int(os.getenv('DB_PORT_REMOTE', '3306')),
    #    'USER': os.getenv('DB_USER_REMOTE', 'postgres'),
    #    'PASSWORD': os.getenv('DB_PASSWORD_REMOTE', ''),
    #    'CERT': os.getenv('DB_CERT_REMOTE', ''),
    #},
    'default': {
        'NAME': 'medistock_db',
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'admin_medistock',
        'PASSWORD': 'te@A9P%Zg&CbbXraXqdy',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'collation': 'utf8mb4_unicode_ci',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}