# Generated by Django 6.0.4 on 2026-04-29 17:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descuento_porcentaje', models.IntegerField(default=0)),
                ('condiciones_pago', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'convenio_institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_receptor', models.CharField(blank=True, max_length=30, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'direccion_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=180)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('giro', models.CharField(blank=True, max_length=180, null=True)),
                ('direccion_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=180, null=True)),
                ('convenio_activo', models.BooleanField(default=False)),
                ('credito_autorizado', models.BooleanField(default=False)),
                ('limite_credito', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_o_pasaporte', models.CharField(max_length=30, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('PARTICULAR', 'Particular'), ('INSTITUCIONAL', 'Institucional')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil_trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
