# Generated by Django 6.0.4 on 2026-05-25 18:19

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.accounts.validators.validar_rut]),
        ),
    ]
