### Login to obtain JWT token
POST http://localhost:8000/api/accounts/login/
Content-Type: application/json

{
    "username": "testuser",
    "password": "Medistock2024!"
}

### Use the obtained token to access the Chilexpress coverage endpoint
GET http://localhost:8000/api/logistics/chilexpress/cobertura/99/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NTc0Mjg5LCJpYXQiOjE3Nzc1NzM5ODksImp0aSI6ImY0ZWQ2NmM2ZGU2NTQ2ODY4YjdiNTk3NzQ5YmY4ODdlIiwidXNlcl9pZCI6IjIiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QG1lZGlzdG9jay5jbCIsImdydXBvcyI6W10sImZ1bGxfbmFtZSI6IlRlc3QgVXNlciJ9.6_3X4U5pOujp45_7ZysbcoYDhyzHKxW9YCmfdxnPXAo

### prueba de cobertura
GET  http://testservices.wschilexpress.com/georeference/api/v1.0/regions


### prueba cobertura calle
POST https://testservices.wschilexpress.com/georeference/api/v1.0/streets/search HTTP/1.1

Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: ccf8cd3e30bc4a8c8e6592c73121d098

{
    "countyName": "SANTIAGO CENTRO",
    "streetName": "DOCTOR ALLENDE PADIN",
    "pointsOfInterestEnabled": true,
    "streetNameEnabled": true,
    "roadType": 0
}

### prueba cobertura comuna
GET https://testservices.wschilexpress.com/georeference/api/v1.0/coverage-areas?RegionCode=RM&type=0 HTTP/1.1

Cache-Control: no-cache
Ocp-Apim-Subscription-Key: ccf8cd3e30bc4a8c8e6592c73121d098



### Cotizar
POST /api/logistics/chilexpress/cotizar/

{
    "origen": "PROV",
    "destino": "LASCD",
    "peso": 2.5,
    "alto": 20,
    "ancho": 15,
    "largo": 30
}