# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_producto', models.CharField(max_length=180)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('descuento', models.IntegerField(default=0)),
                ('monto_neto_linea', models.IntegerField(default=0)),
                ('monto_exento_linea', models.IntegerField(default=0)),
                ('monto_iva_linea', models.IntegerField(default=0)),
                ('monto_total_linea', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detalle_documento_tributario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_dte', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('FIRMADO', 'Firmado'), ('ENVIADO_SII', 'Enviado SII'), ('ACEPTADO_SII', 'Aceptado SII'), ('RECHAZADO_SII', 'Rechazado SII'), ('ENVIADO_CLIENTE', 'Enviado cliente'), ('ANULADO_POR_NOTA_CREDITO', 'Anulado por nota de crédito')], default='BORRADOR', max_length=30)),
                ('monto_neto', models.IntegerField(default=0)),
                ('monto_exento', models.IntegerField(default=0)),
                ('monto_iva', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('tasa_iva', models.IntegerField(default=19)),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='CONTADO', max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('xml_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('track_id_sii', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_sii', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'documento_tributario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributarioEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_emisor', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=180)),
                ('giro', models.CharField(blank=True, max_length=180, null=True)),
                ('direccion_casa_matriz', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'db_table': 'documento_tributario_emisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributarioReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_receptor', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=180)),
                ('giro', models.CharField(blank=True, max_length=180, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'db_table': 'documento_tributario_receptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnvioDteSii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('track_id', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error'), ('REINTENTANDO', 'Reintentando')], default='PENDIENTE', max_length=15)),
                ('respuesta_xml', models.TextField(blank=True, null=True)),
                ('mensaje_error', models.CharField(blank=True, max_length=500, null=True)),
                ('intentos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'envio_dte_sii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDteHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=120)),
                ('fecha_estado', models.DateTimeField(auto_now_add=True)),
                ('respuesta_sii', models.CharField(blank=True, max_length=500, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_dte_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FolioDte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_desde', models.IntegerField()),
                ('folio_hasta', models.IntegerField()),
                ('folio_actual', models.IntegerField()),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo_caf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'folio_dte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_traslado', models.CharField(choices=[('VENTA', 'Venta'), ('TRASLADO_ENTRE_SUCURSALES', 'Traslado entre sucursales'), ('CONSIGNACION', 'Consignación'), ('DEVOLUCION', 'Devolución'), ('OTRO', 'Otro')], default='VENTA', max_length=30)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('rut_transportista', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_transportista', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna_origen', models.CharField(blank=True, max_length=120, null=True)),
                ('comuna_destino', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'guia_despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciaDocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento_referenciado', models.CharField(blank=True, max_length=120, null=True)),
                ('folio_referenciado', models.IntegerField(blank=True, null=True)),
                ('fecha_documento_referenciado', models.DateField(blank=True, null=True)),
                ('tipo_referencia', models.CharField(choices=[('ANULA_DOCUMENTO', 'Anula documento'), ('CORRIGE_MONTO', 'Corrige monto'), ('CORRIGE_TEXTO', 'Corrige texto'), ('REFERENCIA_GUIA', 'Referencia guía'), ('REFERENCIA_ORDEN_COMPRA', 'Referencia orden de compra')], max_length=30)),
                ('razon_referencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'referencia_documento_tributario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sii', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('afecta_iva', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_documento_tributario',
                'managed': False,
            },
        ),
    ]
