# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('RECIBIDA_PARCIAL', 'Recibida parcial'), ('RECIBIDA_TOTAL', 'Recibida total'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.IntegerField(default=0)),
                ('monto_iva', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'compra_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detalle_compra_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=180)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
