# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente_api', models.CharField(max_length=150)),
                ('api_key_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('limite_requests_diario', models.IntegerField(default=1000)),
            ],
            options={
                'db_table': 'api_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntegracionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_integracion', models.CharField(choices=[('PASARELA_PAGO', 'Pasarela de pago'), ('COURIER', 'Courier'), ('SII', 'SII')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('url_base', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integracion_externa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('REQUEST_ENTRANTE', 'Request entrante'), ('REQUEST_SALIENTE', 'Request saliente')], max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registro_integracion',
                'managed': False,
            },
        ),
    ]
