# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('url_etiqueta', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_despacho', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express')], default='NORMAL', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('costo_despacho', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
    ]
