# Generated by Django 6.0.4 on 2026-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aseguradora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('banco_origen', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('monto_reportado', models.IntegerField(default=0)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente revisión'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_REVISION', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comprobante_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConciliacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conciliacion', models.DateTimeField(auto_now_add=True)),
                ('estado_conciliacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('DIFERENCIA_DE_MONTO', 'Diferencia de monto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conciliacion_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cubierto', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pago_aseguradora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=180, null=True)),
                ('metodo_pago', models.CharField(choices=[('WEBPAY', 'WebPay'), ('MERCADOPAGO', 'MercadoPago'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO_INSTITUCIONAL', 'Crédito institucional')], max_length=30)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15)),
                ('monto_confirmado', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transaccion_pago',
                'managed': False,
            },
        ),
    ]
