# Generated by Django 6.0.4 on 2026-05-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={},
        ),
    ]
