# Generated by Django 6.0.4 on 2026-05-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_sucursal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False},
        ),
    ]
