# Generated by Django 6.0.4 on 2026-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_sucursal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunaChilexpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(max_length=10)),
                ('county_name', models.CharField(max_length=100)),
                ('coverage_name', models.CharField(max_length=100)),
                ('retorna_respuesta', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'comunas_chilexpress',
                'managed': False,
            },
        ),
    ]
